#!/usr/bin/env node

require('./babel-register')

const Mocha = require('mocha');
const path = require('path');
const { ENVS } = require('./server/constants');
const argv = require('yargs').argv;

if (argv.only && argv.only !== process.env.NODE_ENV) {
  console.log(`This script can only be run on environment : ${argv.only}, current environment : ${process.env.NODE_ENV}`);
  process.exit(1);
}

process.env.NODE_ENV = process.env.NODE_ENV || ENVS.TEST;

const scriptFile = argv._[0].endsWith('.js') ? argv._[0]: argv._[0] + '.js'

const fullPathScriptFile = path.join(__dirname, '/server/scripts/', scriptFile);

const mocha = new Mocha({
  bail: true,
  ui: 'bdd',
  timeout: process.env.TIMEOUT || 30000,
});

mocha.addFile(fullPathScriptFile);

mocha.run();
