apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-preprod
  name: nginx-svc-preprod
  namespace: preprod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-preprod
status:
  loadBalancer: {}