apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:

  default.conf: |-
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name beta.anonyme.io;
        location / {
        
        rewrite ^/(.*)$ https://www.webflow.com/$1 redirect;
       }
  
    }
