apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jardin-back
  name: jardin-back
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jardin-back
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jardin-back
    spec:
      containers:
      - image: anonymeio/jardin-back:0.0.1
        name: jardin-back
        command: ["/bin/sh", "-c", "npm init-db", "npm init-data","npm run migrate", "npm run serve"]
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: preprod-db
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: preprod-db
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: preprod-db
                key: DB_NAME
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: preprod-db
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: preprod-db
                key: DB_PORT
        resources: {}
status: {}
