apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:

  nginx.conf: |-
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name beta.anonyme.io;
        location / {
        proxy_pass https://webflow.com$request_uri;
        
       }
  
    }
