apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-preprod
  namespace: preprod
data:

  default.conf: |
    server {
        listen 80;
        server_name beta.anonyme.io;
        
        location / {
          proxy_pass http://jardin-svc-preprod:31745;
        }
  
        }