apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-preprod
  namespace: preprod
data:

  default.conf: |-
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name beta.anonyme.io;
        location / {
    
        proxy_pass https://www.webflow.com;
       }
  
    }