apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-preprod
  namespace: preprod
data:

  default.conf: |-
    http {
    upstream {
        server beta.anonyme.io;
    }

    include mime.types;

    server {
        listen 80;
        server_name webflow.com;
        location / {
            proxy_pass https://webflow.com;
        }
     }
    }