apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-prod
  namespace: prod
data:

  nginx.conf: |-
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name beta.anonyme.io;
        location / {
        proxy_pass http://jardin-prod-svc;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
       }
  
    }
