apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: anonyme.io
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: frontend.35.225.226.173.nip.io 
    http:
      paths:
      - backend:
          serviceName: jardin-prod-svc
          servicePort: 3000
        path: /api
      - backend:
          serviceName: nginx-prod
          servicePort: 80
        path: /