apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: argocd
data:

  default.conf: |-
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name anonyme.io;
        location / {
        
        rewrite ^/(anonyme.io)$ https://www.webflow.com/$1 redirect;
       }
  
    }