apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-prod
  namespace: prod
data:

  default.conf: |
    server {
        listen 80;
        server_name anonyme.io;
        
        location / {
          proxy_pass http://10.20.12.102:3000;
        }
  
      }