apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: argocd
data:

  default.conf: |-
    server {
        listen 80;
        server_name anonyme.io;
        
        location / {
          proxy_pass https://webflow.com/$1 redirect;
        }
  
        }