name: Demo workflow

on:
  push:
    branches:
      - demo

jobs:
  DEMO-CI:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: jardin_secret
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: no_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 15432:5432

    strategy:
      matrix:
        node-version: [12.19.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install packege
      run: npm install -g yarn
 
    - name: install dpendencies with yarn
      run: yarn install --frozen-lockfile
    
    - name: Run yarn
      run: npm run yarn
    
    - name: Run migrations
      run: npm run migrate

    - name: run test for application
      run: npm run test

  DEMO-CD:
    needs: [DEMO-CI]
    if: success()
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: DEMO Deployment
      uses: appleboy/ssh-action@master
      with:
        host: 34.69.202.26 
        username: root
        key: ${{ secrets.QA_DEV_SECRET }}
        port: 22
        script: |
          pwd
          cd /root/jardinsecret-back/
          git stash
          git pull origin demo
          /root/.nvm/versions/node/v12.19.0/bin/npm run init-db
          /root/.nvm/versions/node/v12.19.0/bin/npm run init-data
          /root/.nvm/versions/node/v12.19.0/bin/npm run migrate
          pkill -f -SIGHUP nodemon

    
