name: dev workflow

on:
  push:
    branches:
      - test-dev

jobs:
  DEV-CI:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: jardin_secret
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: no_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 15432:5432

    strategy:
      matrix:
        node-version: [12.19.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install packege
        run: npm install -g yarn

      - name: install dpendencies with yarn
        run: yarn install --frozen-lockfile

      - name: Run yarn
        run: npm run yarn

      - name: Run init db
        run: npm run init-db

      - name: Run migrate
        run: npm run migrate

      - name: run test for application
        run: npm run test

  DEV-CD:
    needs: [DEV-CI]
    if: success()
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Dev Deployment
      uses: appleboy/ssh-action@master
      with:
        host: 34.70.252.194
        username: root
        key: ${{ secrets.QA_DEV_SECRET }}
        port: 22
        script_stop: true
        script: |
          screen -X quit
          rm -Rf jardinsecret-back

          git clone -b dev https://${secrets.USER}:${secrets.PASSWORD}@github.com/darkangel01111991/jardinsecret-back.git
          chmod 777 -R jardinsecret-back
          cd jardinsecret-back
          /root/.nvm/versions/node/v12.19.0/bin/npm run reinstall
          /root/.nvm/versions/node/v12.19.0/bin/npm run yarn
          /root/.nvm/versions/node/v12.19.0/bin/npm run init-db
          /root/.nvm/versions/node/v12.19.0/bin/npm run init-data
          /root/.nvm/versions/node/v12.19.0/bin/npm run migrate
          screen -d -m npm run serve







