name: staging workflow

on:
  push:
    branches:
      - dev

jobs:
  DEV-CI:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: jardin_secret
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: no_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 15432:5432

    strategy:
      matrix:
        node-version: [12.19.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install packege
      run: npm install -g yarn
 
    - name: install dpendencies with yarn
      run: yarn install --frozen-lockfile
    
    - name: Run yarn
      run: npm run yarn
    
    - name: Run migrations
      run: npm run migrate

    - name: run test for application
      run: npm run test

  DEV-CD:
    needs: [DEV-CI]
    if: success()
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Dev Deployment
      uses: appleboy/ssh-action@master
      with:
        host: 34.70.252.194 
        username: root
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDddHhxuiaBvPHQlN1Pi20JO6i+2FWlKAH49Eq07+8QZ9qM7DJOPJQ6tqq1TESHjQ9k60e65cliQIYnNZpf15GwQnLiA96AWVAyZVQ6jZLLNzrKuVzPOl+QZ07Cmi4RyvoGVOOIg+6SSoYekg5jvYS3McHqU0vEOMm9NC/doDd9cD2IXS3ME/4RzVAmFAsdi8Vqf2We3ciEfK5eIVfWUcaVF37BEg2WsIS+t2sdjm3jzKG0S5+i6xyiSp8p+76ZMVNRb5NRQQ4kqIwFD7ryhLEnJxaamlEiXXn8Q4Tii4Vu+LPgVYXsMXpoT/r0bxZuEnD6sjJY4Iqoh5bYpVwwtwin qasim@qasim-VirtualBox" #${{ secrets.DEV_SECRET }}
        port: 22
        script: |
          
          pwd
    
