name: master workflow

on:
  push:
    branches:
      - master

jobs:
  master-CI:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: jardin_secret
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: no_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 15432:5432

    strategy:
      matrix:
        node-version: [12.19.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install packege
      run: npm install -g yarn
 
    - name: install dpendencies with yarn
      run: yarn install --frozen-lockfile
    
    - name: Run yarn
      run: npm run yarn
    
    - name: Run migrations
      run: npm run migrate

    - name: run test for application
      run: npm run test

  

    
