name: Docker build for Nodeapp

on:
  push:
    branches:
      - docker-k8s

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker build
      run: |
        docker build . -t ${{secrets.DOCKER_HUB_USERNAME }}/jardin-back:0.0.1
    - name: Docker push images
      run: |
        docker push docker.io/${{secrets.DOCKER_HUB_USERNAME }}/jardin-back:0.0.1
  setup-db:
    needs: [build-job]
    if: success()
    name: setup db
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info
      - name: export prod database
        run: gcloud sql export sql anonyme-prod gs://sql-bucket-anonyme/prod-db --database=jardin_secret
        