name: Docker build for Nodeapp

on:
  push:
    branches:
      - logging

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      env:
        DOCKER_USER: qasim683
        DOCKER_PASSWORD: tst03006891683
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker build
      run: |
        docker build . -t qasim683/jardin-node-api:1.0.0
    - name: Docker push images
      run: |
        docker push docker.io/qasim683/jardin-node-api:1.0.0
 