name: Docker build for Nodeapp

on:
  push:
    branches:
      - prod

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker build
      run: |
        docker build -t ${{secrets.DOCKER_HUB_USERNAME }}/jardin-prod:0.0.3 .
    - name: Docker push images
      run: |
        docker push docker.io/${{secrets.DOCKER_HUB_USERNAME }}/jardin-prod:0.0.3