on:
  push:
    branches:
      - dev-feature
  
name: npm build for jardinsecret
jobs:
  Docker-build-nodejs:
    name: build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.19.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test
        npm lint
      
    